# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picnmix', '0002_auto_20170119_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='view',
            new_name='views',
        ),
    ]
