# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picnmix', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('albumName', models.CharField(max_length=128)),
                ('ownerId', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
