# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='albumId',
        ),
    ]
