# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20170315_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumDesc',
            field=models.CharField(default='', max_length=256),
        ),
    ]
