# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_auto_20170315_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='coverPicture',
        ),
        migrations.AddField(
            model_name='photo',
            name='coverPicture',
            field=models.BooleanField(default=False),
        ),
    ]
