# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picnmix', '0020_album_coverpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='coverPicture',
        ),
    ]
