# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picnmix', '0021_remove_album_coverpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='coverPicture',
            new_name='is_cover_photo',
        ),
    ]
