# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0023_album_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albumDesc',
            new_name='album_description',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='albumId',
            new_name='album_id',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='albumName',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='ownerId',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='sharedUsers',
            new_name='shared_users_as_string',
        ),
    ]
