# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picnmix', '0024_auto_20170316_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='albumId',
            new_name='album_id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photoID',
            new_name='photo_id',
        ),
    ]
