# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnmix', '0025_auto_20170316_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
