# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picnmix', '0026_auto_20170316_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_cover_photo',
        ),
    ]
