# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
