# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20170314_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='sharedUsers',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
