# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_album_sharedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=b'')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Album')),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
