# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_auto_20170315_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='coverPicture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
